export const orbitSliderConfig = [
  {
    id: 'cashewCharge',
    word: 'Charge',
    tagline: 'Crunchy cashew energy bites for a sustained charge throughout your day.',
    background: 'radial-gradient(circle at 20% 20%, #fff 0%, #fef3c7 40%, #fde68a 100%)',
    orbitColor: 'rgba(217,119,6,0.25)',
    accentColor: '#d97706',
    textColor: '#92400e',
    ingredients: ['🥜', '🧈', '🫘', '🟤'],
    productImage: '/assets/Cashew_pack.webp',
    orbitImages: ['/assets/SKU/skuCashewCharge.webp', '/assets/Cashew_pack.webp'],
  },
  {
    id: 'milletMatrix',
    word: 'Fuel',
    tagline: 'Ancient grain millet matrix packed with fibre and essential nutrients.',
    background: 'radial-gradient(circle at 20% 20%, #fff 0%, #d1fae5 40%, #a7f3d0 100%)',
    orbitColor: 'rgba(5,150,105,0.25)',
    accentColor: '#059669',
    textColor: '#065f46',
    ingredients: ['🌾', '🌽', '🌰', '🟢'],
    productImage: '/assets/Millet_pack.webp',
    orbitImages: ['/assets/SKU/skuMilletMatrix.webp', '/assets/Millet_pack.webp', '/assets/SKU/skuCashewCharge.webp'],
  },
  {
    id: 'oatsOctane',
    word: 'Power',
    tagline: 'Oats meet octane — high-energy snacking for an active lifestyle.',
    background: 'radial-gradient(circle at 20% 20%, #fff 0%, #e0e7ff 40%, #c7d2fe 100%)',
    orbitColor: 'rgba(79,70,229,0.25)',
    accentColor: '#4f46e5',
    textColor: '#3730a3',
    ingredients: ['🌾', '🥜', '🍯', '🔵'],
    productImage: '/assets/Oat_Pack.webp',
    orbitImages: ['/assets/SKU/skuOatsOctane.webp', '/assets/Oat_Pack.webp', '/assets/SKU/skuOatsOctane.webp'],
  },
  {
    id: 'powerChunk',
    word: 'Boost',
    tagline: 'Power-packed chunks of nutrition in every single bite.',
    background: 'radial-gradient(circle at 20% 20%, #fff 0%, #fce4ec 40%, #f8bbd0 100%)',
    orbitColor: 'rgba(219,39,119,0.25)',
    accentColor: '#db2777',
    textColor: '#9d174d',
    ingredients: ['🌴', '🍫', '🍊', '🔴'],
    productImage: '/assets/Power_pack.webp',
    orbitImages: ['/assets/SKU/skuPowerChunk.webp', '/assets/Power_pack.webp', '/assets/SKU/skuSeedBoost.webp'],
  },
  {
    id: 'seedBoost',
    word: 'Ignite',
    tagline: 'Seed-based boost for natural energy without the crash.',
    background: 'radial-gradient(circle at 20% 20%, #fff 0%, #ede9fe 40%, #ddd6fe 100%)',
    orbitColor: 'rgba(124,58,237,0.25)',
    accentColor: '#7c3aed',
    textColor: '#5b21b6',
    ingredients: ['🌻', '🎃', '🫘', '🟣'],
    productImage: '/assets/Seed_pack.webp',
    orbitImages: ['/assets/SKU/skuSeedBoost.webp', '/assets/Seed_pack.webp', '/assets/Seed_pack.webp'],
  },
]
